In [1]:
import pandas as pd

In [2]:
#series 
pd.Series((1,2,2,3), name="Age")

0    1
1    2
2    2
3    3
Name: Age, dtype: int64

In [5]:
# dataframe 
# dict 
di={"Name":["anand","mango","pen","mobile"], 
    "Identity":["human","fruit","object","none"]}

df=pd.DataFrame(di)
df

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     none

In [9]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
df.head(2)

    Name Identity
0  anand    human
1  mango    fruit

In [7]:
df.tail(2)

     Name Identity
2     pen   object
3  mobile     none

In [8]:
df.sample(2)

    Name Identity
0  anand    human
2    pen   object

In [10]:
df.head()

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     none

In [11]:
df['Name']

0     anand
1     mango
2       pen
3    mobile
Name: Name, dtype: object

In [12]:
df[["Name", "Identity"]]

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     none

In [13]:
count=[1,10,3,2]
df.insert(0,"count",count)

In [14]:
df

   count    Name Identity
0      1   anand    human
1     10   mango    fruit
2      3     pen   object
3      2  mobile     none

In [15]:
colour = "skin", "orange", "blue","black"

In [16]:
df["colour"]=colour

In [17]:
df["id"]= [1,2,3,4]

In [18]:
df.sample()

   count Name Identity colour  id
2      3  pen   object   blue   3

In [23]:
# new df df2 id, weight
df2 = pd.DataFrame({
    'id': [1,2,3,4,5],
    "weight": [55,62,48,70, None]
})

print(df2)

   id  weight
0   1    55.0
1   2    62.0
2   3    48.0
3   4    70.0
4   5     NaN

In [29]:
# merge or join 
pd.merge(df,df2, how="outer",on="id")

   count    Name Identity  colour  id  weight
0    1.0   anand    human    skin   1    55.0
1   10.0   mango    fruit  orange   2    62.0
2    3.0     pen   object    blue   3    48.0
3    2.0  mobile     none   black   4    70.0
4    NaN     NaN      NaN     NaN   5     NaN

In [ ]:
pd.merge(df,df2,how=)  # set